name: vision_ai
description: An assistive app for visually impaired users that provides real-time environment descriptions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  flutter_tflite: ^1.0.1
  http: ^1.1.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/yolov8n.tflite
    - assets/models/yolov5s_labels.txt
